import type { CorePosState } from './types'

export const state: CorePosState = {
  tableTimers: {},
  tableStatuses: {},
  tableCustomers: {},
  itemCosts: {},
  itemPrices: {},
  inventory: {},
  attendanceEmployees: {},
  attendanceRecords: {},
  tableDrafts: {},
  pendingBatchPreviews: {},
  pendingBatches: {},
  submittedBatches: {},
  staffDrafts: {},
  selectedTable: null,
  currentMode: 'staff',
  activeDraftEntries: [],
  activePendingBatches: [],
  activeSubmittedBatches: [],
  tableSplitCounters: {},
  seatTimerInterval: null,
  currentBuilder: null,
  currentPendingBatchId: null,
  currentPendingTable: null,
  isQrMode: false,
  isHistorySimpleMode: false,
  menuFilter: {
    activeTab: 'menu',
    activeCategoryKey: 'pasta_risotto',
  },
  staffWorkspace: {
    expanded: false,
    serviceFeeEnabled: false,
    discount: null,
  },
  syncLog: [],
}
